version: "3.7"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MODE=production
      - PORT=5000
      - DB_DSN=sql12710664:zqrdjvFhXT@tcp(sql12.freemysqlhosting.net:3306)/sql12710664?charset=utf8mb4&parseTime=True&loc=Local
