version: "3.7"

services:
  db:
    image: mysql:8.0.34-debian
    restart: always
    command: "--innodb_use_native_aio=0 --character-set-server=utf8 --collation-server=utf8_general_ci"
    cap_add: [SYS_NICE]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - mysql:/var/lib/mysql
      - mysql:/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:

volumes:
  mysql:
  redis:
